// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6XmT8uzqo-KJLLxOL_QElJowq_y2gGB8',
    appId: '1:890589980513:web:6f95d0609a62c321c54720',
    messagingSenderId: '890589980513',
    projectId: 'messagingapp-26c68',
    authDomain: 'messagingapp-26c68.firebaseapp.com',
    storageBucket: 'messagingapp-26c68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMuv9j7e-mWDST_fECha2QcXkoxu5zvio',
    appId: '1:890589980513:android:5808d066ecec3ccdc54720',
    messagingSenderId: '890589980513',
    projectId: 'messagingapp-26c68',
    storageBucket: 'messagingapp-26c68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tQXKkFcEUSx2BmN-y1l8l0dlqvar5-g',
    appId: '1:890589980513:ios:001a7bd03a21d55fc54720',
    messagingSenderId: '890589980513',
    projectId: 'messagingapp-26c68',
    storageBucket: 'messagingapp-26c68.appspot.com',
    iosClientId: '890589980513-h8orpdsq4gn79k2li1da1vnqm3bug60j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab15',
  );
}
