// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJlSbtlUCuoogyDuIeQzNvQirxXTURb30',
    appId: '1:649749249561:web:6ec11ff708e97ae29bb488',
    messagingSenderId: '649749249561',
    projectId: 'firstproject-87d85',
    authDomain: 'firstproject-87d85.firebaseapp.com',
    storageBucket: 'firstproject-87d85.appspot.com',
    measurementId: 'G-DLG5NS04CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2jQ-_a7DZb8Dellbuxcia0aRTZCcBxqk',
    appId: '1:649749249561:android:7ebc55004ec037ff9bb488',
    messagingSenderId: '649749249561',
    projectId: 'firstproject-87d85',
    storageBucket: 'firstproject-87d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhZ-oUva2whkHWzWxmXq8P2n4Ap_i9Xg',
    appId: '1:649749249561:ios:fa1c22a80c7a22c89bb488',
    messagingSenderId: '649749249561',
    projectId: 'firstproject-87d85',
    storageBucket: 'firstproject-87d85.appspot.com',
    iosClientId: '649749249561-spl6pt7vu095hmvr6dbsku33bj9mj1e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbProject',
  );
}
