// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBp0AJms5HeGwA7vq9PZ_KwFfOLQ4bug',
    appId: '1:80042738563:web:0928d79462ad8b6911ecb6',
    messagingSenderId: '80042738563',
    projectId: 'student-managment-6677e',
    authDomain: 'student-managment-6677e.firebaseapp.com',
    storageBucket: 'student-managment-6677e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHy2CY12I9t6lMdQBr3ncAMcqKD4-u3Ek',
    appId: '1:80042738563:android:2bad3998a0cec1bf11ecb6',
    messagingSenderId: '80042738563',
    projectId: 'student-managment-6677e',
    storageBucket: 'student-managment-6677e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIK1yzt5qC5QNBVXVnWjPgv9pdCoe3TBk',
    appId: '1:80042738563:ios:3d0ce2af454a607c11ecb6',
    messagingSenderId: '80042738563',
    projectId: 'student-managment-6677e',
    storageBucket: 'student-managment-6677e.appspot.com',
    iosClientId: '80042738563-gqoql3ria6mb2lag78oas5tim11ffjnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectManagment',
  );
}
